---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gene-prod-flask-deployment
  labels:
    username: avlav
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gene-prod-flask
  template:
    metadata:
      labels:
        app: gene-prod-flask
    spec:
      containers:
        - name: flaskdeploys
          imagePullPolicy: Always
          image: kjm24/gene_api:1.0
          env:
          - name: REDIS_IP
            value: gene-prod-redis-service
          ports:
          - name: http
            containerPort: 5000
